---
# File: client.yml - Ansible dependencies for Consul

# Apt cache should be updated here
- name: Install dependencies for configuration by ansible (1/2)
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - python-pip
    - python-setuptools
- name: Install dependencies for configuration by ansible (2/2)
  pip: executable=pip name=python-consul
