---
# File: tasks/Debian.yml - Debian tasks for Consul

- name: "Distribution specific variables"
  include_vars: main.yml

- name: OS packages
  apt: "name={{ item }} state=present update_cache=yes"
  with_items: "{{ consul_debian_os_packages }}"
  tags: installation

- name: Download Consul
  become: no
  connection: local
  get_url: "url={{ consul_zip_url }} dest={{ role_path }}/files/{{ consul_debian_pkg }} sha256sum={{ consul_zip_sha256 }} timeout=74"
  run_once: true
  tags: installation

- name: Unarchive Consul
  become: no
  connection: local
  unarchive: src={{ role_path }}/files/{{ consul_debian_pkg }} dest={{ role_path }}/files/
  run_once: true
  tags: installation

- name: Install Consul
  copy: "src={{ role_path }}/files/consul dest=/usr/local/bin/ owner={{ consul_user }} group={{ consul_group }} mode=0755"
  tags: installation

- name: Cleanup
  become: no
  connection: local
  file: "dest={{ role_path }}/files/consul* state=absent"
  run_once: true
  tags: installation
