---
# File: dirs.yml - Directory settings

- name: Create directories
  file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group}}"
  with_items:
    - /etc/consul
    - /opt/consul
    - /var/consul
    - /var/log/consul
    - /var/run/consul
    - /etc/consul.d
    - /etc/consul.d/bootstrap
    - /etc/consul.d/client
    - /etc/consul.d/server

- name: Ensure bin path
  file:
    path: "{{ consul_bin_path }}"
    state: directory
    owner: root
    mode: 0755
