---
# File: tasks/main.yml - dnsmasq tasks for Consul

- name: Dnsmasq package
  yum: name=dnsmasq state=present
  when: ansible_distribution  == "CentOS" or ansible_distribution  == "RedHat"
  tags: dnsmasq,installation

- name: Dnsmasq package
  apt: name=dnsmasq state=present
  when: ansible_distribution  == "Debian" or ansible_distribution  == "Ubuntu"
  tags: dnsmasq,installation

- name: Stop Dnsmasq
  service: name=dnsmasq state=stopped

- name: "Dnsmasq setup"
  copy: src=../files/dnsmasq-10-consul dest=/etc/dnsmasq.d/10-consul owner=root group=root mode=0644
  tags: dnsmasq
