---
# File: install.yml - package installation tasks for Consul

- name: OS packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ consul_os_packages }}"
  tags: installation

- name: Check Consul package checksum file
  become: no
  local_action:
    stat:
      path: "{{ role_path }}/files/consul_{{ consul_version }}_SHA256SUMS"
  run_once: true
  register: consul_checksum
  tags: installation

- name: Get Consul package checksum file
  become: no
  local_action:
    get_url:
      url: "{{ consul_checksum_file_url }}"
      dest: "{{ role_path }}/files/consul_{{ consul_version }}_SHA256SUMS"
  run_once: true
  tags: installation
  when: consul_checksum.stat.exists == False

- name: Get Consul package checksum
  become: no
  local_action:
    shell: "grep {{ consul_pkg }} {{ role_path }}/files/consul_{{ consul_version }}_SHA256SUMS"
  run_once: true
  register: consul_sha256
  tags: installation

- name: Check Consul package file
  become: no
  local_action:
    stat:
      path: "{{ role_path }}/files/{{ consul_pkg }}"
  run_once: true
  register: consul_package
  tags: installation

- name: Download Consul
  become: no
  local_action:
    get_url:
      url: "{{ consul_zip_url }}"
      dest: "{{ role_path }}/files/{{ consul_pkg }}"
      checksum: "sha256:{{ consul_sha256.stdout.split(' ')|first }}"
      timeout: 42
  run_once: true
  tags: installation
  when: consul_package.stat.exists == False

- name: Unarchive Consul
  become: no
  local_action:
    unarchive:
      src: "{{ role_path }}/files/{{ consul_pkg }}"
      dest: "{{ role_path }}/files/"
      creates: "{{ role_path }}/files/consul"
  run_once: true
  tags: installation

- name: Install Consul
  copy:
    src: "{{ role_path }}/files/consul"
    dest: "{{ consul_bin_path }}/consul"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0755
  tags: installation

- name: Cleanup
  become: no
  local_action:
    file:
      path: "{{ item }}"
      state: absent
  with_fileglob: "{{ role_path }}/files/consul"
  run_once: true
  tags: installation
