---
- name: Get consul info
  ansible.builtin.command:
    cmd: "{{ consul_binary }} info"
  environment:
    CONSUL_HTTP_TOKEN: "{{ consul_acl_agent_token if consul_acl_enable else omit }}"
    CONSUL_HTTP_ADDR: "{{ consul_addresses_http }}:{{ consul_ports_http }}"
  changed_when: false
  register: consul_info_output

- name: Parse Consul leader value
  ansible.builtin.set_fact:
    is_consul_leader: "{{ consul_info_output.stdout | regex_search('leader = (true|false)', '\\1') | first }}"
  when: consul_info_output is defined and consul_info_output.rc == 0

- name: Set consul leader hostname in the rolling restart host inventory
  ansible.builtin.set_fact:
    consul_leader: "{{ inventory_hostname }}"
  delegate_to: "{{ play_hosts[0] }}"
  delegate_facts: true
  when: is_consul_leader is defined and is_consul_leader | bool

- name: Set custom_host_order
  ansible.builtin.set_fact:
    custom_host_order: "{{ (play_hosts | reject('equalto', consul_leader) | list) + [consul_leader] }}"
  when: inventory_hostname == play_hosts[0] and consul_leader is defined and consul_leader != ''

- name: Perform rolling restart for each host
  ansible.builtin.include_tasks: leave_restart_consul_host.yml
  loop: "{{ custom_host_order | default(play_hosts) }}"
  loop_control:
    loop_var: rolling_restart_host
  when: inventory_hostname == play_hosts[0]
