---
# File: tasks/Red Hat.yml - Red Hat tasks for Consul

- name: "Distribution specific variables"
  include_vars: main.yml

- name: OS packages
  yum: "name={{ item }} state=present"
  with_items: "{{ consul_redhat_os_packages }}"
  tags: installation

- name: dnsmasq package
  yum: name=dnsmasq state=present
  when: "consul_dnsmasq == true"
  tags: installation

- name: Download Consul
  get_url: "url={{ consul_zip_url }} dest=/tmp/{{ consul_redhat_pkg }} sha256sum={{ consul_redhat_sha256 }} timeout=74"
  tags: installation

- name: Install Consul
  unarchive: "copy=no creates=/usr/loca/bin/consul src=/tmp/{{ consul_redhat_pkg }} dest=/usr/local/bin/ owner={{ consul_user }} group={{ consul_group }} mode=0755"
  tags: installation

- name: Cleanup
  file: path=/tmp/"{{ consul_redhat_pkg }}" state=absent
  tags: installation
