---
# File: user_group.yml - User and group settings

# Add group
# @TODO

# Add user
- name: Add Consul user
  user:
    name: "{{ consul_user }}"
    comment: "Consul user"
    group: "{{ consul_group }}"
    system: yes
  when: consul_manage_user|bool
