---
# File: main.yml - Handlers for Consul

- name: restart consul
  import_tasks: restart_consul.yml

- name: start consul
  import_tasks: start_consul.yml

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
